version: "3"
services:
  zookeeper:
    container_name: 'local-zookeeper'
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    container_name: 'local-kafka'
    image: 'bitnami/kafka:latest'
    ports:
    - '9092:9092'
    environment:
    - KAFKA_BROKER_ID=1
    - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
    - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
    - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
    - zookeeper
  mongo:
    container_name: 'local-mongo'
    image: 'mongo:latest'
    ports:
    - "27017:27017"
  problem_catalog:
    container_name: 'problem-catalog'
    image: 'isvara/problem-catalog:latest'
    ports:
    - "8081:8081"
    depends_on:
    - kafka
    - mongo
  problem:
    container_name: 'problem'
    image: 'isvara/problem:latest'
    ports:
    - "8080:8080"
    depends_on:
    - kafka
